name: Test

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js 16.x
      uses: actions/setup-node@v3
      with:
        node-version: 16.x

    - name: Install pnpm
      run: npm install -g pnpm

    - name: Install dependencies
      run: pnpm install
    
    - name: Start MySQL service
      run: pnpm db:start

    - name: Run tests
      run: pnpm test

    - name: Run coveralls
      run: pnpm coveralls
      env:
        COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}


